default:	COMPILATION_INST1	COMPILATION_INST2	COMPILATION_INST3	COMPILATION_INST4	

COMPILATION_INST1:	stack.cpp
	g++ -o ex1 -Wall stack.cpp

COMPILATION_INST2:	queue_stack.cpp
	g++ -o ex2 -Wall queue_stack.cpp 

COMPILATION_INST3:	linedlist_to_binary_search_tree.cpp
	g++ -o list_to_tree -Wall linedlist_to_binary_search_tree.cpp

COMPILATION_INST4:	binarysearchtree_to_sorted_linkedlist.cpp
	g++ -o tree_to_list -Wall binarysearchtree_to_sorted_linkedlist.cpp

