default:	COMPILATION_INST1	COMPILATION_INST2	COMPILATION_INST3	COMPILATION_INST4	COMPIATION_INST5	COMPILATION_INST6

COMPILATION_INST1:	a2_p1.cpp
	g++ -o ex1 -Wall a2_p1.cpp

COMPILATION_INST2:	a2_p2.cpp
	g++ -o ex2 -Wall a2_p2.cpp

COMPILATION_INST3:	testWindgauge.cpp
	g++ -o windgauge -Wall testWindgauge.cpp	WindGauge.cpp

COMPILATION_INST4:	a2_p4.cpp
	g++ -o ex4 -Wall a2_p4.cpp

COMPIATION_INST5:	a2_p5.cpp
	g++ -o ex5 -Wall a2_p5.cpp

COMPILATION_INST6:	a2_p6.cpp
	g++ -o ex6 -Wall a2_p6.cpp