default:	a1	a2	a3	a4	a5

a1:	a1_p1.cpp
	g++ -o a1_p1 -Wall a1_p1.cpp

a2:	testStack.cpp
	g++ -o stack -Wall testStack.cpp

a3:	testLinkedList.cpp
	g++ -o linkedlist -Wall testLinkedList.cpp

a4:	a1_p4.cpp
	g++ -o a1_p4 -Wall a1_p4.cpp

a5:	a1_p5.cpp
	g++ -o a1_p5 -Wall a1_p5.cpp